#!/usr/bin/env python3
"""Build the self-contained, attested ligature zipapp (chainlink #57).

Runtime contract: a stdlib `zipapp` targeting a system Python interpreter,
deliberately not PyInstaller/Nuitka. This repository has no runtime
dependency beyond jsonschema/PyYAML and no packaging config; a zipapp is the
smallest build that fits that style. The cost -- a compatible interpreter on
the target machine -- is not hidden: every build records its
`required_python` and `doctor`/`version --verify` check it (see
scripts/adjudicator.py).

The bundle file list is derived **from docs/implementation-inventory.json**,
not a hand-maintained parallel list: every python module, schema, prompt,
schema example, installed template, and required vendored asset whose
`disposition` is `runtime-required` or `installed-template` is copied in
(the installed templates are needed because `ligature init` runs FROM this
artifact and copies them into a target repo). `tests/test_inventory_drift.py`
already fails when the inventory and the real filesystem disagree, so
deriving the bundle from the inventory keeps that guarantee instead of
duplicating it.

Outputs (into --out, default `dist/`):
  ligature.pyz            the executable archive
  SHA256SUMS              sha256 of the archive bytes
  PROVENANCE.json         build/adjudicator metadata + bundle manifest
  NOTICE                  project notice
  THIRD_PARTY_NOTICES.txt vendored component licenses
"""
from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import os
import platform
import shutil
import subprocess
import sys
import tempfile
import zipapp
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import adjudicator  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
INVENTORY_RELPATH = "docs/implementation-inventory.json"
ARTIFACT_NAME = "ligature.pyz"
BUNDLE_DISPOSITIONS = frozenset({"runtime-required", "installed-template"})

_MAIN = '''"""ligature zipapp entrypoint (generated by scripts/build_zipapp.py)."""
import sys

from pipeline import main

if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
'''

_PACKAGE_INIT = '''"""Bundled ligature resources (generated by scripts/build_zipapp.py).

Located at runtime through importlib.resources by scripts/resources.py,
which works whether this package is inside a zipapp or on disk.
"""
'''

_NOTICE = """ligature
=======

This distribution is a self-contained zipapp built from the ligature
workspace. It embeds an attestation of its own contents
(ligature_data/BUILD_ATTESTATION.json); `ligature version --verify` and
`ligature doctor` recompute and check that attestation, and a target
repository's gate_integrity pins the content hash of the executable that
initialized it.

Third-party components bundled with, or invoked by, this distribution are
listed in THIRD_PARTY_NOTICES.txt. This project does not ship a LICENSE
file; treat this artifact's licensing status as undetermined until one is
added by the project owners.
"""


def _git_commit(root: Path) -> str | None:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=root,
            capture_output=True,
            text=True,
            check=True,
        )
        return out.stdout.strip() or None
    except (OSError, subprocess.CalledProcessError):
        return None


def load_inventory(source_root: Path) -> dict:
    return json.loads((source_root / INVENTORY_RELPATH).read_text())


def bundle_entries(inventory: dict) -> list[tuple[str, str]]:
    """[(source-relative path, archive name)] derived solely from the
    inventory's disposition fields."""
    entries: list[tuple[str, str]] = []
    for module in inventory["python_modules"]:
        if module["disposition"] in BUNDLE_DISPOSITIONS:
            entries.append((module["path"], Path(module["path"]).name))
    for key in ("schemas", "schema_examples", "prompts", "documentation_and_templates"):
        for entry in inventory[key]:
            if entry["disposition"] in BUNDLE_DISPOSITIONS:
                entries.append((entry["path"], f"ligature_data/{entry['path']}"))
    for asset in inventory["vendored_runtime_assets"]:
        if asset.get("required_at_runtime"):
            entries.append((asset["path"], f"ligature_data/{asset['path']}"))
    # de-duplicate on archive name (a path is one file regardless of which
    # array names it)
    unique: dict[str, str] = {}
    for source_rel, arcname in entries:
        unique[arcname] = source_rel
    return sorted(((source_rel, arcname) for arcname, source_rel in unique.items()))


# Fixed timestamp for every staged file: the earliest the ZIP format
# supports, so a rebuild produces the same archive bytes.
_FREEZE_EPOCH = 315619200  # 1980-01-02T00:00:00Z (ZIP's 1980 floor + 1 day)


def _freeze(path: Path) -> None:
    os.utime(path, (_FREEZE_EPOCH, _FREEZE_EPOCH))
    os.chmod(path, 0o644)


def _bundle_manifest(staging: Path, attestation_arcname: str) -> dict[str, str]:
    manifest: dict[str, str] = {}
    for path in sorted(staging.rglob("*")):
        if not path.is_file():
            continue
        arcname = path.relative_to(staging).as_posix()
        if arcname == attestation_arcname:
            continue
        manifest[arcname] = "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()
    return manifest


def _bundled_schemas(staging: Path, manifest: dict[str, str]) -> dict[str, str]:
    schemas: dict[str, str] = {}
    prefix = "ligature_data/"
    for arcname in manifest:
        if not (arcname.startswith(prefix) and arcname.endswith(".json")):
            continue
        if "schema" not in Path(arcname).name:
            continue
        data = json.loads((staging / arcname).read_text())
        if isinstance(data, dict):
            schemas[arcname[len(prefix):]] = adjudicator.schema_version_of(data)
    return schemas


def _third_party_notices(inventory: dict, source_root: Path) -> str:
    lines = ["Third-party components", "=====================", ""]
    for asset in inventory["vendored_runtime_assets"]:
        if not asset.get("required_at_runtime"):
            continue
        source = source_root / asset["path"]
        license_path = source.parent.parent / "LICENSE"
        lines.append(f"{asset['path']}")
        lines.append("-" * len(asset["path"]))
        lines.append(asset.get("reason", ""))
        lines.append("")
        if license_path.is_file():
            lines.append(f"License ({license_path.relative_to(source_root).as_posix()}):")
            lines.append("")
            lines.append(license_path.read_text().rstrip())
        else:
            lines.append("No license file was found alongside this component.")
        lines.append("")
    return "\n".join(lines) + "\n"


def build(out_dir: Path, *, source_root: Path = ROOT) -> dict:
    inventory = load_inventory(source_root)
    entries = bundle_entries(inventory)
    missing = [rel for rel, _ in entries if not (source_root / rel).is_file()]
    if missing:
        raise SystemExit(
            "refusing to build: inventory runtime-required file(s) are missing from disk: "
            + ", ".join(sorted(missing))
        )

    staging = Path(tempfile.mkdtemp(prefix="ligature-build-"))
    try:
        for source_rel, arcname in entries:
            destination = staging / arcname
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source_root / source_rel, destination)
        (staging / "ligature_data").mkdir(parents=True, exist_ok=True)
        (staging / "ligature_data" / "__init__.py").write_text(_PACKAGE_INIT)
        (staging / "__main__.py").write_text(_MAIN)
        for path in sorted(staging.rglob("*"), reverse=True):
            if path.is_file():
                _freeze(path)
            else:
                os.utime(path, (_FREEZE_EPOCH, _FREEZE_EPOCH))

        attestation_arcname = adjudicator.ATTESTATION_ARCNAME
        manifest = _bundle_manifest(staging, attestation_arcname)
        content_hash = adjudicator.hash_manifest(manifest)
        attestation = {
            "attestation_version": "1.0",
            "product_name": adjudicator.PRODUCT_NAME,
            "product_version": adjudicator.PRODUCT_VERSION,
            "built_at": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "build_tool": "zipapp",
            "build_toolchain": {
                "python": platform.python_version(),
                "implementation": platform.python_implementation(),
            },
            "required_python": adjudicator.required_python_string(),
            "platform": adjudicator.REQUIRED_PLATFORM,
            "inventory_version": inventory["inventory_version"],
            "inventory_source": INVENTORY_RELPATH,
            "source_commit": _git_commit(source_root),
            "bundle_file_count": len(manifest),
            "bundled_schemas": _bundled_schemas(staging, manifest),
            "content_hash": content_hash,
            "bundle_manifest": manifest,
        }
        attestation_path = staging / attestation_arcname
        attestation_path.write_text(json.dumps(attestation, indent=2, sort_keys=True) + "\n")
        _freeze(attestation_path)

        out_dir.mkdir(parents=True, exist_ok=True)
        artifact = out_dir / ARTIFACT_NAME
        if artifact.exists():
            artifact.unlink()
        zipapp.create_archive(staging, artifact, interpreter="/usr/bin/env python3", compressed=True)
    finally:
        shutil.rmtree(staging, ignore_errors=True)

    artifact_sha256 = "sha256:" + hashlib.sha256(artifact.read_bytes()).hexdigest()
    provenance = {
        "provenance_version": "1.0",
        "product_name": adjudicator.PRODUCT_NAME,
        "product_version": adjudicator.PRODUCT_VERSION,
        "artifact": ARTIFACT_NAME,
        "artifact_sha256": artifact_sha256,
        "content_hash": content_hash,
        "build_command": "python3 scripts/build_zipapp.py --out <dir>",
        "runtime_contract": "zipapp targeting a system Python interpreter",
        "required_python": adjudicator.required_python_string(),
        "source_commit": _git_commit(source_root),
        "bundle_manifest_derivation": (
            "docs/implementation-inventory.json dispositions runtime-required, "
            "installed-template, and required_at_runtime vendored assets"
        ),
        "bundle_file_count": len(manifest),
        "bundled_schemas": attestation["bundled_schemas"],
        "third_party_notices": "THIRD_PARTY_NOTICES.txt",
    }
    (out_dir / "SHA256SUMS").write_text(f"{artifact_sha256.split(':', 1)[1]}  {ARTIFACT_NAME}\n")
    (out_dir / "PROVENANCE.json").write_text(json.dumps(provenance, indent=2, sort_keys=True) + "\n")
    (out_dir / "NOTICE").write_text(_NOTICE)
    (out_dir / "THIRD_PARTY_NOTICES.txt").write_text(_third_party_notices(inventory, source_root))

    return {
        "artifact": str(artifact),
        "artifact_sha256": artifact_sha256,
        "content_hash": content_hash,
        "bundle_file_count": len(manifest),
        "bundled_schemas": attestation["bundled_schemas"],
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--out", type=Path, default=ROOT / "dist", help="output directory (default: dist/)")
    args = parser.parse_args(argv)
    result = build(args.out.resolve())
    print(f"built: {result['artifact']}")
    print(f"artifact sha256: {result['artifact_sha256']}")
    print(f"content hash:    {result['content_hash']}")
    print(f"bundled files:   {result['bundle_file_count']}")
    print(f"bundled schemas: {len(result['bundled_schemas'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
