#!/usr/bin/env python3
"""Deterministic promotion-receipt generation (plan.md §7.1, chainlink
#45) -- Stage 4.5. NOT an LLM draft, and NOT routed through
scripts/review_checkpoint.py's approve()/approve_pair(): a promotion
receipt is generated by reading an already-accepted artifact set and
computing the manifest, not drafted and reviewed the way a boundary
contract is. approve()'s own review injection writes a NESTED
{"review": {...}} block; docs/promotion-receipt-schema.json requires
TOP-LEVEL reviewer/accepted_at, has no `review` property at all, and
additionalProperties: false -- approve()'s own write would be rejected
outright by this schema. scripts/validate_promotion_receipt.py's own
docstring already establishes that promotion receipts are standalone,
not routed through draft/approve, for exactly this reason.

External review history (high severity throughout):

  Round 2: promotion_id and schema_versions were free-form CLI arguments
  copied into the receipt verbatim -- "PROM-WRONG-999",
  {"boundary": "999.0"} both passed the real validator with zero
  findings. Fixed: promotion_id is now always computed from `cluster`
  alone (compute_promotion_id); schema_versions is computed by reading
  each accepted artifact's own `schema_version` field.

  Round 3: schema_versions still trusted an unvalidated artifact's
  self-declared schema_version -- {"schema_version": "999.0", "garbage":
  true} under a `_boundaries/` directory produced a receipt declaring
  "boundary": "999.0" with zero findings; policy_version was still a
  free-form argument, only checked against an accepted artifact's
  filename *stem*, so "reliance-policy@9.9" passed with
  docs/reliance-policy.md present regardless of its content. Fixed:
  every accepted artifact under a recognized kind directory is now
  validated before its schema_version is trusted; policy_version is
  read from the accepted policy document's own "Policy version:" marker
  line (docs/reliance-policy.template.md), not supplied as an argument.

  Round 4 (this pass), two more fail-open paths:

  (a) High -- the round-3 fix validated each artifact with NO crate or
      workspace cross-file context (interactions_by_id, R2's boundary/
      exemption coverage, evidence ids), so validate_data() degraded
      G2/G15/R2/etc. to non-blocking info findings for every artifact --
      a *reviewed* exemption referencing a nonexistent interaction still
      passed, since only a hand-authored review block was needed to
      satisfy the schema's own required `review` field. Fixed:
      accept_promotion() now loads the real project descriptor and
      builds the SAME per-crate cross-file context
      pipeline.py's own cmd_validate_interaction/cmd_validate_exemption/
      cmd_validate_protocol_debt build (via the same
      valid_boundary_edges_from_crate/valid_exemption_interaction_ids_from_crate/
      valid_interaction_ids_from_crate/load_interactions_by_id/
      valid_evidence_ids functions those commands already use) --
      G2/G15/R2/G11/etc. now run for real, fail-closed, against every
      accepted artifact that has one.

  (b) Medium -- artifact kind was determined from the immediate parent
      directory's *basename* alone, so a fully schema-valid boundary
      contract at `junk/_boundaries/<id>.json` (nowhere near any crate's
      real boundary directory) still had its schema_version recorded.
      Fixed: kind is now determined by matching the artifact's resolved
      parent directory against the project descriptor's own canonical
      directories (project_descriptor.py's *_dir_for helpers) -- the
      exact same anchoring discipline every validate_*.py module's own
      crate-wide scan already uses. An artifact that merely sits under a
      directory *named* `_boundaries` etc., without being the crate's
      real one, contributes nothing to schema_versions (same as any
      other non-kind file) rather than being trusted.

A second, independent finding from the second review pass: the receipt
used to be written before the audit log was appended, so a failure
writing the audit entry (a bad review_log path, a full disk) left an
accepted-but-unaudited receipt installed -- reproduced directly with a
directory in place of review_log. accept_promotion() now prepares the
audit append and the receipt write as one transaction, mirroring
review_checkpoint.py's own approve_pair(): the audit entry is durably
appended first, the receipt is swapped into place with a temp-file +
os.replace, and either an audit-append failure (nothing else touched
yet) or a receipt-write failure (rolls the audit entry back) leaves the
workspace exactly as it was before the call -- never an accepted receipt
with no corresponding audit trail.

A third, medium-severity finding from the same pass: review_log's old
default (review_checkpoint.REVIEW_LOG_DEFAULT, "ci/results/review_log.jsonl")
resolves relative to the process's cwd, not `workspace_root` --
accepting a promotion for an external or temporary workspace silently
wrote its audit trail into whatever repo the CLI happened to be invoked
from. review_log now defaults to `workspace_root / "ci" / "results" /
"review_log.jsonl"` unless the caller overrides it.

A third finding from round 4 (low severity): extract_policy_version()
used to return the *first* regex match, so a policy document containing
two conflicting "Policy version:" lines silently picked one. Fixed:
exactly one marker line is now required.

Chainlink #82 (the Stage 4.5 instance of the unenforceable-human-
checkpoint gap): accept_promotion() had no review-provenance guard. It
required only a non-empty `--reviewer` string, then deterministically
computed hashes/promotion_id/schema_versions and validated the receipt
-- but validate_data() checks hashes, containment and cross-references,
never WHERE a review block came from, so a receipt could be minted over
every artifact in the accepted set the moment anyone supplied a name,
including review blocks written out-of-band by an unattended agent and
ruled unauthorized. The guard added here reads each accepted artifact's
own `review` block back against ci/results/review_log.jsonl -- the
append-only audit trail review_checkpoint.approve() writes, and the only
record that a review event happened through the sanctioned path -- via
review_checkpoint.review_provenance_gaps(); a block with no matching
approval entry refuses the whole acceptance (PromotionReceiptError,
nothing written). The last gate before the write transaction, so every
other refusal still fires first with its own real reason.

The same issue's second remedy is in this module too: a human-ruling
gate. Provenance proves where a review block came from; it cannot ask
whether a human has ruled on the SET being promoted, because an
unattended agent's own `approve` run leaves perfectly valid provenance
entries behind (the date-creusot pilot's eight contested blocks all have
them) and artifacts with no `review` block at all -- evidence records
promoted outside any tool path -- are invisible to it by construction.
So accept_promotion() ALSO requires, for every manifest entry, a
`ratified` human ruling over that exact version of the file
(ruling_gaps(), reading ci/results/human_rulings.jsonl), recorded by
record_ruling() / the `record-ruling` CLI command: missing, rejected,
stale (the file changed since the ruling), an unrecognized verdict, or
an unreadable log all refuse, with nothing written. That is what makes
the pilot README's own constraint -- "#14's accept-promotion must not
run before rulings 1 and 2 land" -- mechanically true rather than
prose.
"""
from __future__ import annotations

import hashlib
import json
import os
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from ligature_install import POLICY_VERSION_MARKER_RE  # noqa: E402
from ligature_install import safe_target  # noqa: E402
from project_descriptor import boundary_dir_for  # noqa: E402
from project_descriptor import conflict_dir_for  # noqa: E402
from project_descriptor import evidence_dir_for  # noqa: E402
from project_descriptor import exemption_dir_for  # noqa: E402
from project_descriptor import interaction_dir_for  # noqa: E402
from project_descriptor import load_project_descriptor  # noqa: E402
from project_descriptor import protocol_debt_dir_for  # noqa: E402
from review_checkpoint import ApprovalRefused  # noqa: E402
from review_checkpoint import review_provenance_gaps  # noqa: E402
from validate_boundary_contracts import load_validator as _load_boundary_validator  # noqa: E402
from validate_boundary_contracts import validate_data as _validate_boundary_data  # noqa: E402
from validate_boundary_contracts import valid_boundary_edges_from_crate  # noqa: E402
from validate_conflict_resolution import load_validator as _load_conflict_resolution_validator  # noqa: E402
from validate_conflict_resolution import validate_data as _validate_conflict_resolution_data  # noqa: E402
from validate_evidence import load_validator as _load_evidence_validator  # noqa: E402
from validate_evidence import validate_data as _validate_evidence_data  # noqa: E402
from validate_evidence import valid_evidence_ids  # noqa: E402
from validate_exemption import load_validator as _load_exemption_validator  # noqa: E402
from validate_exemption import validate_data as _validate_exemption_data  # noqa: E402
from validate_exemption import valid_exemption_interaction_ids_from_crate  # noqa: E402
from validate_interaction import load_interactions_by_id  # noqa: E402
from validate_interaction import load_validator as _load_interaction_validator  # noqa: E402
from validate_interaction import validate_data as _validate_interaction_data  # noqa: E402
from validate_promotion_receipt import RequiredWitnessError  # noqa: E402
from validate_promotion_receipt import is_generated_review_projection  # noqa: E402
from validate_promotion_receipt import load_validator  # noqa: E402
from validate_promotion_receipt import required_witness_paths  # noqa: E402
from validate_promotion_receipt import validate_data  # noqa: E402
from validate_protocol_debt import load_validator as _load_protocol_debt_validator  # noqa: E402
from validate_protocol_debt import validate_data as _validate_protocol_debt_data  # noqa: E402
from validate_protocol_debt import valid_interaction_ids_from_crate  # noqa: E402
from validate_witness import CANONICAL_DIR_NAME as _WITNESS_DIR_NAME  # noqa: E402
from validate_witness import load_validator as _load_witness_validator  # noqa: E402
from validate_witness import validate_data as _validate_witness_data  # noqa: E402
from validate_witness import witness_dir_for  # noqa: E402
from validate_witness import witness_promotion_digest  # noqa: E402


class PromotionReceiptError(Exception):
    """A workspace/path/metadata problem discovered while computing the
    receipt -- distinct from ApprovalRefused (a fully computed receipt
    that then fails the real validator): this is refusing to even
    attempt generation from bad input, the same "loud failure over
    silent nonsense" discipline scripts/validate_promotion_receipt.py
    itself uses for a missing workspace root."""


def _sha256(file_path: Path) -> str:
    return "sha256:" + hashlib.sha256(file_path.read_bytes()).hexdigest()


def _witness_promotion_hash_if_applicable(
    descriptor: dict | None, workspace_root: Path, entry_path: str, resolved: Path
) -> str | None:
    """None means "not a witness artifact -- use the ordinary byte
    hash." A non-None return is `validate_witness.witness_promotion_digest`,
    computed only after confirming the spec is genuinely valid (G1a/G1b,
    and G2 with the owning crate's real specs_search_root) at its real
    canonical crate directory -- never trusted merely because its path
    happens to end in the right shape (plan.md §16.5, chainlink #35).

    Fails closed (PromotionReceiptError), rather than silently falling
    back to an ordinary byte hash, for anything that LOOKS like a
    witness (its immediate parent directory is literally named
    "_witnesses", validate_witness.py's own CANONICAL_DIR_NAME) but
    isn't genuinely one: no descriptor was supplied to confirm crate
    anchoring at all; the directory doesn't match any declared crate's
    real canonical witness_dir_for (outside its canonical directory);
    or the spec fails validate_witness.py's own G1a/G1b/G2 bar."""
    looks_like_witness = resolved.parent.name == _WITNESS_DIR_NAME
    if descriptor is None:
        if looks_like_witness:
            raise PromotionReceiptError(
                f"artifact path {entry_path!r} sits under a {_WITNESS_DIR_NAME!r} directory but no "
                "project descriptor was supplied to confirm it is a real crate's canonical witness "
                "directory -- refusing to treat it as an ordinary artifact"
            )
        return None

    for crate in descriptor["crates"]:
        if resolved.parent != witness_dir_for(crate, workspace_root):
            continue
        specs_search_root = workspace_root / crate["specs_search_root"]
        try:
            data = json.loads(resolved.read_text())
        except (json.JSONDecodeError, UnicodeDecodeError) as e:
            raise PromotionReceiptError(f"witness spec {entry_path!r} is not readable JSON: {e}")
        if not isinstance(data, dict):
            raise PromotionReceiptError(f"witness spec {entry_path!r} is not a JSON object")
        findings = _validate_witness_data(resolved, data, _load_witness_validator(), specs_search_root)
        errors = [f for f in findings if f.severity == "error"]
        if errors:
            raise PromotionReceiptError(
                f"witness spec {entry_path!r} does not pass its own witness validator, refusing to "
                "accept it into this promotion or trust its content:\n"
                + "\n".join(f"  - {f}" for f in errors)
            )
        return witness_promotion_digest(data)

    if looks_like_witness:
        raise PromotionReceiptError(
            f"artifact path {entry_path!r} sits under a {_WITNESS_DIR_NAME!r} directory but not at "
            "any declared crate's own canonical witness directory -- a witness spec outside its "
            "canonical directory is refused, not silently treated as an ordinary artifact"
        )
    return None


def compute_artifact_manifest(
    workspace_root: Path, artifact_paths: list[str], descriptor: dict | None = None
) -> list[dict]:
    """Deterministically compute artifact_manifest entries for
    `artifact_paths` (workspace-relative strings) -- the exact accepted
    set, no globs, no implicit discovery (plan.md §7.1: "the manifest
    states the exact set"). Every path is checked for workspace
    containment, exactly mirroring
    scripts/validate_promotion_receipt.py's own check_artifact_manifest
    -- generating a receipt that couldn't possibly pass its own
    validator would defeat the point of generating it deterministically.

    A bad path (escapes the workspace, aliases another entry, doesn't
    exist) is a hard failure here, not a finding to report later --
    there is no "generate first, let the validator catch it" step for a
    path that was never valid to begin with.

    `descriptor` (chainlink #35, optional and backward-compatible --
    omitting it reproduces this function's original, witness-unaware
    behavior exactly) recognizes canonical crate-scoped witness specs
    and hashes them with `validate_witness.witness_promotion_digest`
    instead of a plain byte hash, so a rendering-only regeneration
    (output.render_hash alone changing) never invalidates the receipt
    while a fixture or determinism.value_hash change still does. Every
    other artifact keeps the exact byte-hash behavior this function has
    always had."""
    workspace_resolved = workspace_root.resolve()
    manifest: list[dict] = []
    seen_resolved: dict[Path, str] = {}
    for entry_path in artifact_paths:
        if entry_path.startswith("/") or ".." in entry_path.split("/"):
            raise PromotionReceiptError(
                f"artifact path {entry_path!r} is not workspace-relative -- "
                "absolute paths and .. segments are refused"
            )
        resolved = (workspace_root / entry_path).resolve()
        try:
            resolved.relative_to(workspace_resolved)
        except ValueError:
            raise PromotionReceiptError(f"artifact path {entry_path!r} resolves outside the workspace")
        if resolved in seen_resolved:
            raise PromotionReceiptError(
                f"artifact paths {entry_path!r} and {seen_resolved[resolved]!r} resolve to the same "
                "file -- the accepted set must be exact, not contain duplicates or aliases"
            )
        seen_resolved[resolved] = entry_path
        if not resolved.is_file():
            raise PromotionReceiptError(f"artifact path {entry_path!r} does not exist")
        if is_generated_review_projection(workspace_root, entry_path, resolved):
            raise PromotionReceiptError(
                f"artifact path {entry_path!r} is a generated review projection (a witness rendering, "
                "the contact sheet, or the feature ledger) -- plan.md §16.6: these are review "
                "projections, never promotion inputs, and must never be listed in artifact_manifest"
            )
        witness_hash = _witness_promotion_hash_if_applicable(descriptor, workspace_root, entry_path, resolved)
        manifest.append({"path": entry_path, "hash": witness_hash or _sha256(resolved)})
    return manifest


def compute_promotion_id(cluster: str) -> str:
    """Deterministically derive promotion_id from `cluster` alone --
    mechanical, not a free-form caller-supplied string. `cluster` is
    itself schema-constrained to `^[a-z][a-z0-9-]*$` (docs/promotion-receipt-schema.json),
    so uppercasing it always yields a value starting with a letter and
    containing only [A-Z0-9-] -- exactly what promotion_id's own
    `^PROM-[A-Z][A-Z0-9-]*-[0-9]{3}$` pattern needs, with no separate
    validation required here (a malformed `cluster` is still caught by
    G1a on the assembled receipt before anything is written).

    No promotion lineage/sequence concept is modeled anywhere else in
    this pipeline, so the numeric suffix is always "001" -- this keeps
    promotion_id stable across a cluster's re-acceptances, which matters
    because other artifacts (docs/work-package-manifest-schema.json's
    own provenance.promotion_id) reference it by value; a promotion_id
    that changed on every re-acceptance would strand those references."""
    return f"PROM-{cluster.upper()}-001"


def _locate_artifact(descriptor: dict, workspace_root: Path, resolved: Path) -> tuple[str, dict | None] | None:
    """Determine an accepted artifact's kind (and crate, if crate-scoped)
    by matching its resolved parent directory against the project
    descriptor's own canonical directories -- project_descriptor.py's
    *_dir_for helpers, the exact same anchoring every validate_*.py
    module's own crate-wide scan already uses. External review, medium
    severity, fourth pass: matching by directory *basename* alone (e.g.
    parent.name == "_boundaries") let a fully schema-valid boundary
    contract at `junk/_boundaries/<id>.json` -- nowhere near any crate's
    real boundary directory -- have its schema_version trusted. A path
    that isn't under any crate's or the workspace's real canonical
    directory returns None (contributes nothing to schema_versions),
    exactly like any other non-kind artifact -- it is not specially
    rejected, since compute_artifact_manifest() already accepted it as
    an opaque hashed file; it simply isn't treated as a trustworthy kind
    instance."""
    if resolved.parent == evidence_dir_for(workspace_root):
        return "evidence", None
    if resolved.parent == conflict_dir_for(workspace_root):
        return "conflict_resolution", None
    for crate in descriptor["crates"]:
        if resolved.parent == boundary_dir_for(crate, workspace_root):
            return "boundary", crate
        if resolved.parent == interaction_dir_for(crate, workspace_root):
            return "interaction", crate
        if resolved.parent == exemption_dir_for(crate, workspace_root):
            return "exemption", crate
        if resolved.parent == protocol_debt_dir_for(crate, workspace_root):
            return "protocol_debt", crate
        if resolved.parent == witness_dir_for(crate, workspace_root):
            return "witness", crate
    return None


def _crate_context(crate: dict, workspace_root: Path, cache: dict[str, dict]) -> dict:
    """Real per-crate cross-file context -- interactions_by_id, G15's
    protocol-debt coverage, R2's boundary/exemption coverage -- built
    from the SAME functions pipeline.py's own cmd_validate_interaction/
    cmd_validate_exemption/cmd_validate_protocol_debt use, not
    re-derived ad hoc. Memoized per crate_dir since multiple accepted
    artifacts commonly belong to the same crate."""
    crate_dir = crate["crate_dir"]
    if crate_dir in cache:
        return cache[crate_dir]
    crate_root = (workspace_root / crate_dir).resolve()
    specs_search_root = workspace_root / crate["specs_search_root"]
    interactions_by_id = load_interactions_by_id(interaction_dir_for(crate, workspace_root))
    context = {
        "specs_search_root": specs_search_root,
        "interactions_by_id": interactions_by_id,
        "valid_debt_interaction_ids": valid_interaction_ids_from_crate(
            crate_root, protocol_debt_dir_for(crate, workspace_root), interactions_by_id
        ),
        "covering_boundary_edges": valid_boundary_edges_from_crate(
            crate_root, boundary_dir_for(crate, workspace_root), specs_search_root
        ),
        "valid_exemption_interaction_ids": valid_exemption_interaction_ids_from_crate(
            crate_root, exemption_dir_for(crate, workspace_root), interactions_by_id
        ),
    }
    cache[crate_dir] = context
    return context


def _validate_accepted_artifact(
    kind: str,
    crate: dict | None,
    path: Path,
    data: dict,
    workspace_root: Path,
    crate_context_cache: dict[str, dict],
    evidence_ids_cache: dict[str, set[str]],
) -> list:
    """Validate an accepted artifact against its own real, kind-specific
    validator WITH real cross-file context -- G2/G2+/G2++/G15/R2/G11 all
    run for real here, fail-closed, the same as Stage 4
    (pipeline.py's own cmd_validate_*) and approve(). External review,
    high severity, fourth pass: the previous version called each
    validator with no crate/workspace context at all, degrading every
    cross-file gate to a non-blocking info finding -- a *reviewed*
    exemption referencing a nonexistent interaction still passed, since
    only the schema's own required `review` field needed to be
    satisfied by hand."""
    if kind == "evidence":
        return _validate_evidence_data(path, data, _load_evidence_validator())
    if kind == "conflict_resolution":
        if "evidence_ids" not in evidence_ids_cache:
            evidence_ids_cache["evidence_ids"] = valid_evidence_ids(evidence_dir_for(workspace_root))
        return _validate_conflict_resolution_data(
            path, data, _load_conflict_resolution_validator(), evidence_ids_cache["evidence_ids"]
        )

    assert crate is not None  # every other kind is crate-scoped by _locate_artifact's own contract
    if kind == "witness":
        # No cross-file context needed (unlike boundary/interaction/
        # exemption/protocol_debt) -- validate_witness.py's own G2 needs
        # only the owning crate's specs_search_root, not
        # interactions_by_id/coverage sets, so _crate_context()'s
        # heavier per-crate graph is not built for this kind.
        specs_search_root = workspace_root / crate["specs_search_root"]
        return _validate_witness_data(path, data, _load_witness_validator(), specs_search_root)
    context = _crate_context(crate, workspace_root, crate_context_cache)
    if kind == "boundary":
        return _validate_boundary_data(path, data, _load_boundary_validator(), context["specs_search_root"])
    if kind == "interaction":
        return _validate_interaction_data(
            path, data, _load_interaction_validator(),
            context["valid_debt_interaction_ids"], context["covering_boundary_edges"],
            context["valid_exemption_interaction_ids"],
        )
    if kind == "exemption":
        return _validate_exemption_data(
            path, data, _load_exemption_validator(), context["interactions_by_id"]
        )
    if kind == "protocol_debt":
        return _validate_protocol_debt_data(
            path, data, _load_protocol_debt_validator(), context["interactions_by_id"]
        )
    raise AssertionError(f"unreachable: unknown kind {kind!r}")  # pragma: no cover


def compute_schema_versions(workspace_root: Path, descriptor: dict, artifact_paths: list[str]) -> dict[str, str]:
    """Deterministically compute schema_versions by validating each
    accepted artifact -- against its own real validator, WITH real
    cross-file context (_validate_accepted_artifact) -- and reading the
    `schema_version` it declares. Not a caller-supplied guess, not
    trusted from an unvalidated file, and not trusted from a file that
    merely sits under a directory sharing a kind's basename
    (_locate_artifact requires the real, descriptor-derived canonical
    location).

    An artifact located at a recognized kind's canonical directory that
    fails its own validator (error-severity findings) refuses the whole
    computation -- a promotion cannot silently exclude a broken artifact
    while still accepting it into artifact_manifest; it must be
    genuinely valid or the acceptance is refused outright. An artifact
    at no recognized canonical location contributes nothing. Two
    artifacts of the same kind declaring different schema_version
    values, once both are confirmed valid, is an internal inconsistency
    within this promotion and is refused too."""
    crate_context_cache: dict[str, dict] = {}
    evidence_ids_cache: dict[str, set[str]] = {}
    versions: dict[str, str] = {}
    for entry_path in artifact_paths:
        resolved = (workspace_root / entry_path).resolve()
        located = _locate_artifact(descriptor, workspace_root, resolved)
        if located is None:
            continue
        kind, crate = located

        try:
            data = json.loads(resolved.read_text())
        except (json.JSONDecodeError, UnicodeDecodeError, OSError) as e:
            raise PromotionReceiptError(
                f"{entry_path!r} sits at a recognized {kind!r} directory but is not readable, "
                f"parseable JSON: {e}"
            )
        if not isinstance(data, dict):
            raise PromotionReceiptError(
                f"{entry_path!r} sits at a recognized {kind!r} directory but is not a JSON object"
            )

        findings = _validate_accepted_artifact(
            kind, crate, resolved, data, workspace_root, crate_context_cache, evidence_ids_cache
        )
        errors = [f for f in findings if getattr(f, "severity", "error") == "error"]
        if errors:
            raise PromotionReceiptError(
                f"{entry_path!r} does not pass its own {kind} validator -- refusing to accept it into "
                "this promotion or trust its schema_version:\n"
                + "\n".join(f"  - {f}" for f in errors)
            )

        version = data.get("schema_version")
        if version is None:
            raise PromotionReceiptError(
                f"{entry_path!r} passed its own {kind} validator but declares no schema_version"
            )
        if kind in versions and versions[kind] != version:
            raise PromotionReceiptError(
                f"accepted artifacts disagree on {kind!r} schema_version: {versions[kind]!r} vs "
                f"{version!r} (from {entry_path!r})"
            )
        versions[kind] = version
    if not versions:
        raise PromotionReceiptError(
            "could not compute schema_versions from the accepted artifact set -- no accepted artifact "
            "sits at a recognized canonical directory (a crate's _boundaries/_interactions/_exemptions/"
            "_protocol_debt, or the workspace's evidence/_conflicts) with its own schema_version field"
        )
    return versions


def extract_policy_version(workspace_root: Path, policy_path: str) -> str:
    """Mechanically read policy_version from the accepted policy
    document's own content (docs/reliance-policy.template.md's own
    "Policy version: <name>@<major>.<minor>" line) -- not a free-form
    caller-supplied argument, and not just checked against an accepted
    artifact's filename stem.

    Exactly one marker line is required. External review, low severity,
    fourth pass: the previous version returned the *first* regex match,
    so a policy document containing two different "Policy version:"
    lines (e.g. "reliance-policy@1.2" and "reliance-policy@9.9") was
    silently accepted as whichever came first -- ambiguous, not
    verified. Zero matches or more than one are both hard stops.

    chainlink #78: the path is resolved through ligature_install's own
    safe_target first, so an absolute path or a `../` traversal can no
    longer read a policy document from OUTSIDE the workspace (the
    descriptor's `compatibility_policy.reliance_policy_path` pointing at
    e.g. /etc/hostname used to be read and hashed as if it were the
    project's policy)."""
    try:
        resolved = safe_target(workspace_root, policy_path)
    except Exception as e:
        raise PromotionReceiptError(f"policy document {policy_path!r} is not a safe workspace-relative path: {e}")
    try:
        text = resolved.read_text()
    except OSError as e:
        raise PromotionReceiptError(f"could not read policy document {policy_path!r}: {e}")
    matches = POLICY_VERSION_MARKER_RE.findall(text)
    if len(matches) != 1:
        raise PromotionReceiptError(
            f"{policy_path!r} must have exactly one 'Policy version: <name>@<major>.<minor>' marker "
            f"line (docs/reliance-policy.template.md's own convention) -- found {len(matches)}"
        )
    return matches[0]


def collect_review_blocks(workspace_root: Path, artifact_paths: list[str]) -> dict[str, dict]:
    """Every accepted artifact that carries its own non-empty `review`
    block, keyed by its workspace-relative path -- exactly the set a
    review-provenance check has to prove (chainlink #82).

    Artifacts that carry no `review` block are simply absent, never
    "assumed proven": the reliance policy document (a normative markdown
    file) and evidence records (docs/evidence-schema.json has no `review`
    property at all) have nothing to prove, while
    boundary/interaction/exemption/protocol-debt/bridge/witness/
    conflict-resolution artifacts all do.

    Concept specs moved from the first list to the second in chainlink
    #105, which gave `approve` a concept-spec branch: they now carry the
    same `review` block every other normative artifact does, so a spec in
    an accepted manifest is provenanced rather than silently exempt. That
    is the intended consequence -- an unreviewed concept spec is an
    unreviewed vocabulary for every obligation id in the promotion. The
    one place that matters for the block's shape is
    scripts/validate_concept_spec.py, which READS it from
    docs/boundary-contract-schema.json's own `$defs/review` rather than
    defining a second one.

    Path strings are returned exactly as the caller supplied them, so
    review_provenance_gaps() compares them against the audit entries'
    own target_path values without a second round of normalization.

    An artifact whose bytes do not parse as a JSON/YAML object is
    skipped rather than refused: whether such a file is a valid
    artifact of its kind is the kind validators' question, and they
    have already had their say by the time this runs
    (compute_schema_versions, then the receipt validator above). Only
    an artifact that actually HAS a review block is this check's
    business -- and for every recognized kind, G1a requires exactly
    that block before anything else reaches here."""
    reviewed: dict[str, dict] = {}
    for entry_path in artifact_paths:
        resolved = (workspace_root / entry_path).resolve()
        suffix = resolved.suffix.lower()
        if suffix not in {".json", ".yaml", ".yml"}:
            continue
        try:
            text = resolved.read_text()
        except (OSError, UnicodeDecodeError):
            continue
        try:
            data = json.loads(text) if suffix == ".json" else yaml.safe_load(text)
        except Exception:  # noqa: BLE001 -- any parse failure means "no review block to prove here"
            continue
        if not isinstance(data, dict):
            continue
        review = data.get("review")
        if isinstance(review, dict) and review:
            reviewed[entry_path] = review
    return reviewed


def build_receipt(
    promotion_id: str,
    cluster: str,
    reviewer: str,
    policy_version: str,
    schema_versions: dict[str, str],
    artifact_manifest: list[dict],
    accepted_at: str | None = None,
) -> dict:
    """Assemble a promotion-receipt/1.0 document. Pure data assembly --
    no filesystem access, no validation; accept_promotion() below does
    both, in that order."""
    return {
        "schema": "promotion-receipt/1.0",
        "promotion_id": promotion_id,
        "cluster": cluster,
        "reviewer": reviewer,
        "policy_version": policy_version,
        "schema_versions": schema_versions,
        "accepted_at": accepted_at or datetime.now(timezone.utc).date().isoformat(),
        "artifact_manifest": artifact_manifest,
    }


def _rollback_audit_log(review_log: Path, existed: bool, original_size: int) -> None:
    """Undo a prepared audit append while preserving the prior log --
    mirrors review_checkpoint.py's own approve_pair()-internal helper of
    the same shape, kept as an independent copy here rather than a
    cross-module import of a name that module treats as private."""
    if existed:
        with review_log.open("r+b") as stream:
            stream.truncate(original_size)
            stream.flush()
            os.fsync(stream.fileno())
    else:
        review_log.unlink(missing_ok=True)


def accept_promotion(
    workspace_root: Path,
    cluster: str,
    reviewer: str,
    policy_path: str | None,
    artifact_paths: list[str],
    descriptor_path: Path | None = None,
    accepted_at: str | None = None,
    review_log: Path | None = None,
    ruling_log: Path | None = None,
) -> Path:
    """The dedicated Stage 4.5 acceptance operation (chainlink #45).

    `descriptor_path` defaults to `workspace_root / "project-descriptor.json"`
    (the same convention pipeline.py's own global --descriptor flag
    uses) -- its crates are what compute_schema_versions() anchors
    canonical directories and cross-file validation context to. Loading
    it, and therefore this whole operation, fails closed
    (ProjectDescriptorError propagates) if the descriptor is missing or
    invalid; a promotion cannot be accepted without knowing the real
    crate layout to validate against.

    `policy_path` (e.g. "docs/reliance-policy.md") must itself be one of
    `artifact_paths` -- its own content is where policy_version is read
    from (extract_policy_version), not a caller-supplied guess. It
    defaults to the descriptor's own
    `compatibility_policy.reliance_policy_path` (chainlink #78), and an
    explicit path that disagrees with that declaration is refused.

    Writes to <workspace_root>/specs/_promotions/<cluster>.json -- the
    same canonical directory scripts/validate_promotion_receipt.py's own
    check_naming anchors to. `review_log` defaults to
    `workspace_root / "ci" / "results" / "review_log.jsonl"` -- NOT
    review_checkpoint.REVIEW_LOG_DEFAULT, which is cwd-relative and so
    would silently write an external workspace's audit trail into
    whatever repo this happened to be invoked from.

    Refuses (PromotionReceiptError) before touching the filesystem at
    all if an artifact path, an artifact's own validity (including its
    real cross-file gates), the policy document, or -- chainlink #35 --
    the required witness set is bad: every declared (witness_required:
    true) feature belonging to `cluster` and having its own genuinely
    valid, unambiguous witness spec (validate_promotion_receipt.
    required_witness_paths(), reusing chainlink #29/#30's own
    descriptor-backed discovery and shared verbatim with that module's
    own validator so the two can never disagree about completeness)
    must be present in `artifact_paths`, or generation refuses outright
    rather than producing a receipt that silently omits evidence that
    was part of what was reviewed.

    Finally -- chainlink #82 -- a review-provenance check: every accepted
    artifact carrying its own `review` block must have a matching entry
    in the approval audit log (review_checkpoint.review_provenance_gaps,
    reading `review_log`), i.e. the block must have been produced by the
    sanctioned approve path rather than typed into the file. A `review`
    block is self-asserted data; without this check any non-empty
    `--reviewer` argument was enough to mint a Stage 4.5 receipt over
    artifacts nobody approved through `approve`, including ones whose
    review blocks a human has ruled unauthorized. Artifacts with no
    `review` block (the policy document, evidence records) have nothing to
    prove; concept specs joined the provenanced side in chainlink #105,
    when `approve` gained a concept-spec branch. Refuses
    (PromotionReceiptError) with the offending artifacts named, and writes
    nothing.

    Then -- chainlink #82's second remedy, the human-ruling gate -- every
    artifact in the manifest must be covered by a recorded human ruling
    with verdict `ratified` over that exact version of the file
    (ruling_gaps, reading `ruling_log`, which defaults to
    `workspace_root / "ci" / "results" / "human_rulings.jsonl"`), written
    by record_ruling()/`record-ruling`. Provenance above asks "did the
    sanctioned approve path produce this review block?"; this asks "has a
    human ruled on THIS accepted set?". The two are deliberately
    independent: an approve() entry can exist for an artifact an
    unattended agent approved (the date-creusot pilot's eight contested
    blocks), and artifacts with no `review` block at all -- evidence
    records promoted outside any tool path (the pilot's ruling 2) --
    escape provenance entirely, so neither question answers the pilot's
    "must not run before rulings 1 and 2 land". A missing ruling, a
    `rejected` ruling, a ruling over an older version of the file, or an
    unreadable/damaged rulings log all refuse, and nothing is written.

    Refuses (ApprovalRefused) without writing anything if the assembled receipt
    fails the real validator. Once past all of those checks, the audit entry and
    the receipt write happen as one transaction: the audit append is
    durable before the receipt is swapped into place, and a failure
    swapping the receipt in rolls the audit entry back -- there is no
    window where an accepted receipt exists with no corresponding audit
    entry, or vice versa. Returns the path written."""
    if not reviewer:
        raise ValueError("accept_promotion() requires a non-empty reviewer -- no default, no LLM-supplied value")
    if descriptor_path is None:
        descriptor_path = workspace_root / "project-descriptor.json"
    if review_log is None:
        review_log = workspace_root / "ci" / "results" / "review_log.jsonl"

    descriptor = load_project_descriptor(descriptor_path)

    # chainlink #78: --policy-path defaults to the descriptor's own
    # compatibility_policy.reliance_policy_path, and an explicit path that
    # disagrees with the declaration is refused -- a workspace must not be
    # able to promote against a different policy document than the one it
    # declares. (The field used to be read by nothing: the flag was the
    # only binding, so a correct descriptor and a promotion against some
    # other policy document could coexist silently.)
    declared_policy_path = None
    compat = descriptor.get("compatibility_policy")
    if isinstance(compat, dict):
        value = compat.get("reliance_policy_path")
        if isinstance(value, str) and value:
            declared_policy_path = value
    if policy_path is None:
        if declared_policy_path is None:
            raise PromotionReceiptError(
                "no --policy-path given and the project descriptor declares no "
                "compatibility_policy.reliance_policy_path to default to"
            )
        policy_path = declared_policy_path
    elif declared_policy_path is not None and policy_path != declared_policy_path:
        raise PromotionReceiptError(
            f"--policy-path {policy_path!r} disagrees with the project descriptor's "
            f"compatibility_policy.reliance_policy_path {declared_policy_path!r}"
        )
    if policy_path not in artifact_paths:
        raise PromotionReceiptError(
            f"policy_path {policy_path!r} must itself be one of the accepted artifacts"
        )

    try:
        required_witnesses = required_witness_paths(descriptor, workspace_root, cluster)
    except RequiredWitnessError as e:
        raise PromotionReceiptError(str(e))
    missing_witnesses = sorted(set(required_witnesses) - set(artifact_paths))
    if missing_witnesses:
        raise PromotionReceiptError(
            "declared (witness_required: true) feature(s) have a genuinely valid witness spec that "
            "is not included in this promotion's accepted artifact set: " + ", ".join(missing_witnesses)
        )

    target_path = workspace_root / "specs" / "_promotions" / f"{cluster}.json"
    artifact_manifest = compute_artifact_manifest(workspace_root, artifact_paths, descriptor)
    schema_versions = compute_schema_versions(workspace_root, descriptor, artifact_paths)
    policy_version = extract_policy_version(workspace_root, policy_path)
    promotion_id = compute_promotion_id(cluster)
    receipt = build_receipt(
        promotion_id=promotion_id,
        cluster=cluster,
        reviewer=reviewer,
        policy_version=policy_version,
        schema_versions=schema_versions,
        artifact_manifest=artifact_manifest,
        accepted_at=accepted_at,
    )

    validator = load_validator()
    findings = validate_data(target_path, receipt, validator, workspace_root, descriptor)
    errors = [f for f in findings if getattr(f, "severity", "error") == "error"]
    if errors:
        raise ApprovalRefused(
            f"generated promotion receipt fails validation, refusing to write {target_path}:\n"
            + "\n".join(f"  - {f}" for f in errors)
        )

    # chainlink #82 -- the review-provenance guard, last gate before the
    # write transaction. validate_data() above checks hashes, containment
    # and cross-references; it never asks WHERE a review block came from,
    # and a hand-written `{"reviewer": ...}` is indistinguishable on disk
    # from one approve() wrote. So the accepted set's own review blocks
    # are checked against the approval audit log -- the record of the
    # sanctioned approve path -- before anything is minted. Runs after
    # every other refusal so a genuinely broken artifact is still refused
    # for its real reason first, and before the audit append so a refusal
    # leaves the workspace untouched.
    provenance_gaps = review_provenance_gaps(
        workspace_root, collect_review_blocks(workspace_root, artifact_paths), review_log
    )
    if provenance_gaps:
        raise PromotionReceiptError(
            "refusing to mint a promotion receipt over review block(s) with no approval provenance "
            "(the review must have been recorded through the sanctioned `approve` path):\n"
            + "\n".join(f"  - {gap}" for gap in provenance_gaps)
        )

    # chainlink #82's second remedy -- the human-ruling gate, also last
    # before the write transaction. Provenance proves each review block's
    # ORIGIN; this proves a human has ruled on the accepted set itself,
    # which is what covers artifacts provenance cannot see (evidence
    # records promoted outside any tool path) and artifacts an
    # unattended agent pushed through `approve`. Deliberately AFTER the
    # provenance check, so an artifact with a genuinely unprovenanced
    # review block is still refused for that reason first.
    if ruling_log is None:
        ruling_log = _ruling_log_path(workspace_root)
    ruling_problems = ruling_gaps(workspace_root, artifact_manifest, ruling_log)
    if ruling_problems:
        raise PromotionReceiptError(
            "refusing to mint a promotion receipt: no complete human ruling covers this accepted set "
            "(Stage 4.5 is gated on an explicit `record-ruling` verdict for every artifact):\n"
            + "\n".join(f"  - {gap}" for gap in ruling_problems)
        )

    payload = json.dumps(receipt, indent=2) + "\n"
    audit_line = json.dumps(
        {
            "target_path": str(target_path),
            "classification": "generated",
            "reviewer": reviewer,
            "reviewed_at": receipt["accepted_at"],
            "validation": "checked",
            "logged_at": datetime.now(timezone.utc).isoformat(),
        }
    ) + "\n"

    target_path.parent.mkdir(parents=True, exist_ok=True)
    review_log.parent.mkdir(parents=True, exist_ok=True)

    log_existed = review_log.exists()
    original_log_size = review_log.stat().st_size if log_existed else 0
    audit_touched = False
    try:
        with review_log.open("a") as stream:
            audit_touched = True
            stream.write(audit_line)
            stream.flush()
            os.fsync(stream.fileno())
    except Exception:
        if audit_touched:
            _rollback_audit_log(review_log, log_existed, original_log_size)
        raise

    fd, temp_name = tempfile.mkstemp(prefix=f".{target_path.name}.", suffix=".pending", dir=target_path.parent)
    temp_path = Path(temp_name)
    try:
        with os.fdopen(fd, "w") as stream:
            stream.write(payload)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temp_path, target_path)
    except Exception:
        temp_path.unlink(missing_ok=True)
        _rollback_audit_log(review_log, log_existed, original_log_size)
        raise

    return target_path


RULING_VERDICTS = ("ratified", "rejected")
"""The closed vocabulary a human ruling may use. `ratified` means "I read
this artifact and it may be promoted as it stands"; `rejected` means it
must not be -- accept-promotion still refuses a rejected artifact, with a
message that says so, so a rejection is a recorded decision rather than a
silent absence (the pilot's ruling 1 is exactly this shape: eight review
blocks a human must ratify or reject, not quietly promote)."""


def _ruling_log_path(workspace_root: Path) -> Path:
    """Where rulings live. Workspace-scoped from the start, applying the
    cwd-relative lesson #45 already taught accept_promotion()'s audit-log
    default rather than re-learning it here."""
    return workspace_root / "ci" / "results" / "human_rulings.jsonl"


def record_ruling(
    workspace_root: Path,
    artifact_paths: list[str],
    reviewer: str,
    verdict: str,
    descriptor_path: Path | None = None,
    ruled_at: str | None = None,
    ruling_log: Path | None = None,
) -> dict:
    """Record an explicit human ruling over an exact accepted-artifact
    set (chainlink #82's human-ruling gate) -- the counterpart
    accept_promotion() requires before it will mint a receipt.

    This is the remedy the provenance check cannot be: provenance asks
    whether each `review` block was produced by the sanctioned approve
    path, but an unattended agent can run `approve` too (the date-creusot
    pilot's eight contested blocks all have matching audit entries), and
    artifacts with no `review` block at all -- evidence records promoted
    outside any tool path -- escape provenance by construction. A ruling
    is a separate, explicitly named human event over the SET being
    promoted, so neither question can stand in for it.

    The recorded hashes come from compute_artifact_manifest() -- the same
    containment, alias and witness-promotion-digest rules
    accept_promotion() uses -- so a ruling's `artifacts[].hash` IS the
    hash the gate later compares the receipt's manifest against: ratify,
    then edit the file, and the ruling no longer applies until re-ruled.

    `reviewer` must be a non-empty name (a ruling with no named human is
    not a ruling, same rule as approve()/accept_promotion()), `verdict`
    must be one of RULING_VERDICTS, `ruled_at` a YYYY-MM-DD date. The
    descriptor must load (fail closed, like accept-promotion): its crates
    are what anchors the manifest computation. Appends one entry to
    `ruling_log` (default `workspace_root/ci/results/human_rulings.jsonl`)
    and returns the entry written.

    Deliberately NOT a validation pass: kind validators still run in
    accept_promotion(), so ruling on a broken artifact cannot smuggle it
    past G1a/G1b -- a ruling records a decision, never a check result."""
    if not reviewer:
        raise ValueError("record_ruling() requires a non-empty reviewer -- a ruling with no named human is not a ruling")
    if verdict not in RULING_VERDICTS:
        raise PromotionReceiptError(
            f"ruling verdict {verdict!r} must be one of: {', '.join(RULING_VERDICTS)}"
        )
    if not artifact_paths:
        raise PromotionReceiptError("record_ruling() requires at least one artifact to rule on")
    if ruled_at is None:
        ruled_at = datetime.now(timezone.utc).date().isoformat()
    else:
        try:
            if datetime.strptime(ruled_at, "%Y-%m-%d").strftime("%Y-%m-%d") != ruled_at:
                raise ValueError(ruled_at)
        except (TypeError, ValueError):
            raise PromotionReceiptError(f"--ruled-at {ruled_at!r} must be a YYYY-MM-DD date")
    if descriptor_path is None:
        descriptor_path = workspace_root / "project-descriptor.json"
    descriptor = load_project_descriptor(descriptor_path)
    if ruling_log is None:
        ruling_log = _ruling_log_path(workspace_root)

    artifacts = compute_artifact_manifest(workspace_root, artifact_paths, descriptor)
    entry = {
        "artifacts": artifacts,
        "verdict": verdict,
        "reviewer": reviewer,
        "ruled_at": ruled_at,
        "logged_at": datetime.now(timezone.utc).isoformat(),
    }
    ruling_log.parent.mkdir(parents=True, exist_ok=True)
    with ruling_log.open("a") as stream:
        stream.write(json.dumps(entry) + "\n")
        stream.flush()
        os.fsync(stream.fileno())
    return entry


def ruling_gaps(workspace_root: Path, artifact_manifest: list[dict], ruling_log: Path) -> list[str]:
    """Check an assembled receipt manifest against the human-ruling log
    (chainlink #82's Stage 4.5 gate). Returns one message per artifact
    that is not covered by a `ratified` ruling over this exact version of
    the file; an empty list means the whole set is ruled.

    Failure semantics mirror review_provenance_gaps(): fail closed, no
    default, no cwd-relative path -- a missing, unreadable or damaged
    rulings log proves no ruling, so it refuses. Only entries shaped like
    something record_ruling() would have written (an `artifacts` list and
    a `verdict`) count as rulings at all; the LAST ruling naming an
    artifact wins, so a human can supersede an earlier decision in either
    direction (reject after ratify, ratify after reject) without editing
    the append-only log.

    Trust model, same as the review log: an audit trail, not a signature.
    What it forecloses is promotion by default -- Stage 4.5 now needs a
    named human's recorded verdict before it can write anything."""
    if not artifact_manifest:
        return []

    try:
        text = ruling_log.read_text()
    except FileNotFoundError:
        return [
            f"no human ruling log at {ruling_log} -- none of the {len(artifact_manifest)} artifact(s) about to be "
            "promoted has been ruled on: " + ", ".join(item["path"] for item in artifact_manifest)
            + "; record the ruling first with `record-ruling --reviewer <name> "
            "--verdict ratified|rejected --artifact <path> [--artifact <path> ...]`"
        ]
    except OSError as e:
        return [f"human ruling log {ruling_log} cannot be read, so no ruling can be proven: {e}"]

    entries: list[dict] = []
    for lineno, line in enumerate(text.splitlines(), start=1):
        if not line.strip():
            continue
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            return [
                f"human ruling log {ruling_log} line {lineno} is not valid JSON, so the log cannot be read "
                "as the ruling trail it is -- fix or remove the damaged line before promoting"
            ]
        if not isinstance(entry, dict) or not isinstance(entry.get("artifacts"), list) or "verdict" not in entry:
            continue  # not a ruling entry -- irrelevant lines are not this check's business to reject
        entries.append(entry)

    # Latest ruling per artifact wins. Keyed by RESOLVED path, so a
    # differently-spelled but identical path still matches -- the same
    # discipline _entry_path_matches() applies to the review log.
    latest: dict[Path, tuple[object, dict]] = {}
    for entry in entries:
        for item in entry["artifacts"]:
            if not isinstance(item, dict) or not isinstance(item.get("path"), str):
                continue
            latest[(workspace_root / item["path"]).resolve()] = (item.get("hash"), entry)

    gaps: list[str] = []
    for item in artifact_manifest:
        path = item["path"]
        hit = latest.get((workspace_root / path).resolve())
        if hit is None:
            gaps.append(
                f"{path}: no human ruling recorded for this artifact -- record one with "
                f"`record-ruling --reviewer <name> --verdict ratified --artifact {path}`"
            )
            continue
        ruling_hash, entry = hit
        verdict = entry.get("verdict")
        if verdict == "rejected":
            gaps.append(
                f"{path}: a human ruling REJECTED this artifact (ruled by {entry.get('reviewer')!r} at "
                f"{entry.get('ruled_at')!r}) -- a rejected artifact must not be promoted; drop it from the "
                "accepted set, or record a new ruling over it if the decision changed"
            )
        elif verdict not in RULING_VERDICTS:
            gaps.append(
                f"{path}: the recorded ruling's verdict {verdict!r} is not one of {', '.join(RULING_VERDICTS)} "
                "-- an unrecognized verdict cannot satisfy the gate"
            )
        elif ruling_hash != item["hash"]:
            gaps.append(
                f"{path}: the ratified ruling was recorded over a different version of this artifact "
                f"(ruled {ruling_hash!r}, current {item['hash']!r}) -- re-run `record-ruling` after the "
                "change so the ruling covers what is actually being promoted"
            )
    return gaps
