#!/usr/bin/env python3
"""Deterministic promotion-receipt generation (plan.md §7.1, chainlink
#45) -- Stage 4.5. NOT an LLM draft, and NOT routed through
scripts/review_checkpoint.py's approve()/approve_pair(): a promotion
receipt is generated by reading an already-accepted artifact set and
computing the manifest, not drafted and reviewed the way a boundary
contract is. approve()'s own review injection writes a NESTED
{"review": {...}} block; docs/promotion-receipt-schema.json requires
TOP-LEVEL reviewer/accepted_at, has no `review` property at all, and
additionalProperties: false -- approve()'s own write would be rejected
outright by this schema. scripts/validate_promotion_receipt.py's own
docstring already establishes that promotion receipts are standalone,
not routed through draft/approve, for exactly this reason.

External review history (high severity throughout):

  Round 2: promotion_id and schema_versions were free-form CLI arguments
  copied into the receipt verbatim -- "PROM-WRONG-999",
  {"boundary": "999.0"} both passed the real validator with zero
  findings. Fixed: promotion_id is now always computed from `cluster`
  alone (compute_promotion_id); schema_versions is computed by reading
  each accepted artifact's own `schema_version` field.

  Round 3: schema_versions still trusted an unvalidated artifact's
  self-declared schema_version -- {"schema_version": "999.0", "garbage":
  true} under a `_boundaries/` directory produced a receipt declaring
  "boundary": "999.0" with zero findings; policy_version was still a
  free-form argument, only checked against an accepted artifact's
  filename *stem*, so "reliance-policy@9.9" passed with
  docs/reliance-policy.md present regardless of its content. Fixed:
  every accepted artifact under a recognized kind directory is now
  validated before its schema_version is trusted; policy_version is
  read from the accepted policy document's own "Policy version:" marker
  line (docs/reliance-policy.template.md), not supplied as an argument.

  Round 4 (this pass), two more fail-open paths:

  (a) High -- the round-3 fix validated each artifact with NO crate or
      workspace cross-file context (interactions_by_id, R2's boundary/
      exemption coverage, evidence ids), so validate_data() degraded
      G2/G15/R2/etc. to non-blocking info findings for every artifact --
      a *reviewed* exemption referencing a nonexistent interaction still
      passed, since only a hand-authored review block was needed to
      satisfy the schema's own required `review` field. Fixed:
      accept_promotion() now loads the real project descriptor and
      builds the SAME per-crate cross-file context
      pipeline.py's own cmd_validate_interaction/cmd_validate_exemption/
      cmd_validate_protocol_debt build (via the same
      valid_boundary_edges_from_crate/valid_exemption_interaction_ids_from_crate/
      valid_interaction_ids_from_crate/load_interactions_by_id/
      valid_evidence_ids functions those commands already use) --
      G2/G15/R2/G11/etc. now run for real, fail-closed, against every
      accepted artifact that has one.

  (b) Medium -- artifact kind was determined from the immediate parent
      directory's *basename* alone, so a fully schema-valid boundary
      contract at `junk/_boundaries/<id>.json` (nowhere near any crate's
      real boundary directory) still had its schema_version recorded.
      Fixed: kind is now determined by matching the artifact's resolved
      parent directory against the project descriptor's own canonical
      directories (project_descriptor.py's *_dir_for helpers) -- the
      exact same anchoring discipline every validate_*.py module's own
      crate-wide scan already uses. An artifact that merely sits under a
      directory *named* `_boundaries` etc., without being the crate's
      real one, contributes nothing to schema_versions (same as any
      other non-kind file) rather than being trusted.

A second, independent finding from the second review pass: the receipt
used to be written before the audit log was appended, so a failure
writing the audit entry (a bad review_log path, a full disk) left an
accepted-but-unaudited receipt installed -- reproduced directly with a
directory in place of review_log. accept_promotion() now prepares the
audit append and the receipt write as one transaction, mirroring
review_checkpoint.py's own approve_pair(): the audit entry is durably
appended first, the receipt is swapped into place with a temp-file +
os.replace, and either an audit-append failure (nothing else touched
yet) or a receipt-write failure (rolls the audit entry back) leaves the
workspace exactly as it was before the call -- never an accepted receipt
with no corresponding audit trail.

A third, medium-severity finding from the same pass: review_log's old
default (review_checkpoint.REVIEW_LOG_DEFAULT, "ci/results/review_log.jsonl")
resolves relative to the process's cwd, not `workspace_root` --
accepting a promotion for an external or temporary workspace silently
wrote its audit trail into whatever repo the CLI happened to be invoked
from. review_log now defaults to `workspace_root / "ci" / "results" /
"review_log.jsonl"` unless the caller overrides it.

A third finding from round 4 (low severity): extract_policy_version()
used to return the *first* regex match, so a policy document containing
two conflicting "Policy version:" lines silently picked one. Fixed:
exactly one marker line is now required.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from project_descriptor import boundary_dir_for  # noqa: E402
from project_descriptor import conflict_dir_for  # noqa: E402
from project_descriptor import evidence_dir_for  # noqa: E402
from project_descriptor import exemption_dir_for  # noqa: E402
from project_descriptor import interaction_dir_for  # noqa: E402
from project_descriptor import load_project_descriptor  # noqa: E402
from project_descriptor import protocol_debt_dir_for  # noqa: E402
from review_checkpoint import ApprovalRefused  # noqa: E402
from validate_boundary_contracts import load_validator as _load_boundary_validator  # noqa: E402
from validate_boundary_contracts import validate_data as _validate_boundary_data  # noqa: E402
from validate_boundary_contracts import valid_boundary_edges_from_crate  # noqa: E402
from validate_conflict_resolution import load_validator as _load_conflict_resolution_validator  # noqa: E402
from validate_conflict_resolution import validate_data as _validate_conflict_resolution_data  # noqa: E402
from validate_evidence import load_validator as _load_evidence_validator  # noqa: E402
from validate_evidence import validate_data as _validate_evidence_data  # noqa: E402
from validate_evidence import valid_evidence_ids  # noqa: E402
from validate_exemption import load_validator as _load_exemption_validator  # noqa: E402
from validate_exemption import validate_data as _validate_exemption_data  # noqa: E402
from validate_exemption import valid_exemption_interaction_ids_from_crate  # noqa: E402
from validate_interaction import load_interactions_by_id  # noqa: E402
from validate_interaction import load_validator as _load_interaction_validator  # noqa: E402
from validate_interaction import validate_data as _validate_interaction_data  # noqa: E402
from validate_promotion_receipt import RequiredWitnessError  # noqa: E402
from validate_promotion_receipt import is_generated_review_projection  # noqa: E402
from validate_promotion_receipt import load_validator  # noqa: E402
from validate_promotion_receipt import required_witness_paths  # noqa: E402
from validate_promotion_receipt import validate_data  # noqa: E402
from validate_protocol_debt import load_validator as _load_protocol_debt_validator  # noqa: E402
from validate_protocol_debt import validate_data as _validate_protocol_debt_data  # noqa: E402
from validate_protocol_debt import valid_interaction_ids_from_crate  # noqa: E402
from validate_witness import CANONICAL_DIR_NAME as _WITNESS_DIR_NAME  # noqa: E402
from validate_witness import load_validator as _load_witness_validator  # noqa: E402
from validate_witness import validate_data as _validate_witness_data  # noqa: E402
from validate_witness import witness_dir_for  # noqa: E402
from validate_witness import witness_promotion_digest  # noqa: E402


class PromotionReceiptError(Exception):
    """A workspace/path/metadata problem discovered while computing the
    receipt -- distinct from ApprovalRefused (a fully computed receipt
    that then fails the real validator): this is refusing to even
    attempt generation from bad input, the same "loud failure over
    silent nonsense" discipline scripts/validate_promotion_receipt.py
    itself uses for a missing workspace root."""


def _sha256(file_path: Path) -> str:
    return "sha256:" + hashlib.sha256(file_path.read_bytes()).hexdigest()


def _witness_promotion_hash_if_applicable(
    descriptor: dict | None, workspace_root: Path, entry_path: str, resolved: Path
) -> str | None:
    """None means "not a witness artifact -- use the ordinary byte
    hash." A non-None return is `validate_witness.witness_promotion_digest`,
    computed only after confirming the spec is genuinely valid (G1a/G1b,
    and G2 with the owning crate's real specs_search_root) at its real
    canonical crate directory -- never trusted merely because its path
    happens to end in the right shape (plan.md §16.5, chainlink #35).

    Fails closed (PromotionReceiptError), rather than silently falling
    back to an ordinary byte hash, for anything that LOOKS like a
    witness (its immediate parent directory is literally named
    "_witnesses", validate_witness.py's own CANONICAL_DIR_NAME) but
    isn't genuinely one: no descriptor was supplied to confirm crate
    anchoring at all; the directory doesn't match any declared crate's
    real canonical witness_dir_for (outside its canonical directory);
    or the spec fails validate_witness.py's own G1a/G1b/G2 bar."""
    looks_like_witness = resolved.parent.name == _WITNESS_DIR_NAME
    if descriptor is None:
        if looks_like_witness:
            raise PromotionReceiptError(
                f"artifact path {entry_path!r} sits under a {_WITNESS_DIR_NAME!r} directory but no "
                "project descriptor was supplied to confirm it is a real crate's canonical witness "
                "directory -- refusing to treat it as an ordinary artifact"
            )
        return None

    for crate in descriptor["crates"]:
        if resolved.parent != witness_dir_for(crate, workspace_root):
            continue
        specs_search_root = workspace_root / crate["specs_search_root"]
        try:
            data = json.loads(resolved.read_text())
        except (json.JSONDecodeError, UnicodeDecodeError) as e:
            raise PromotionReceiptError(f"witness spec {entry_path!r} is not readable JSON: {e}")
        if not isinstance(data, dict):
            raise PromotionReceiptError(f"witness spec {entry_path!r} is not a JSON object")
        findings = _validate_witness_data(resolved, data, _load_witness_validator(), specs_search_root)
        errors = [f for f in findings if f.severity == "error"]
        if errors:
            raise PromotionReceiptError(
                f"witness spec {entry_path!r} does not pass its own witness validator, refusing to "
                "accept it into this promotion or trust its content:\n"
                + "\n".join(f"  - {f}" for f in errors)
            )
        return witness_promotion_digest(data)

    if looks_like_witness:
        raise PromotionReceiptError(
            f"artifact path {entry_path!r} sits under a {_WITNESS_DIR_NAME!r} directory but not at "
            "any declared crate's own canonical witness directory -- a witness spec outside its "
            "canonical directory is refused, not silently treated as an ordinary artifact"
        )
    return None


def compute_artifact_manifest(
    workspace_root: Path, artifact_paths: list[str], descriptor: dict | None = None
) -> list[dict]:
    """Deterministically compute artifact_manifest entries for
    `artifact_paths` (workspace-relative strings) -- the exact accepted
    set, no globs, no implicit discovery (plan.md §7.1: "the manifest
    states the exact set"). Every path is checked for workspace
    containment, exactly mirroring
    scripts/validate_promotion_receipt.py's own check_artifact_manifest
    -- generating a receipt that couldn't possibly pass its own
    validator would defeat the point of generating it deterministically.

    A bad path (escapes the workspace, aliases another entry, doesn't
    exist) is a hard failure here, not a finding to report later --
    there is no "generate first, let the validator catch it" step for a
    path that was never valid to begin with.

    `descriptor` (chainlink #35, optional and backward-compatible --
    omitting it reproduces this function's original, witness-unaware
    behavior exactly) recognizes canonical crate-scoped witness specs
    and hashes them with `validate_witness.witness_promotion_digest`
    instead of a plain byte hash, so a rendering-only regeneration
    (output.render_hash alone changing) never invalidates the receipt
    while a fixture or determinism.value_hash change still does. Every
    other artifact keeps the exact byte-hash behavior this function has
    always had."""
    workspace_resolved = workspace_root.resolve()
    manifest: list[dict] = []
    seen_resolved: dict[Path, str] = {}
    for entry_path in artifact_paths:
        if entry_path.startswith("/") or ".." in entry_path.split("/"):
            raise PromotionReceiptError(
                f"artifact path {entry_path!r} is not workspace-relative -- "
                "absolute paths and .. segments are refused"
            )
        resolved = (workspace_root / entry_path).resolve()
        try:
            resolved.relative_to(workspace_resolved)
        except ValueError:
            raise PromotionReceiptError(f"artifact path {entry_path!r} resolves outside the workspace")
        if resolved in seen_resolved:
            raise PromotionReceiptError(
                f"artifact paths {entry_path!r} and {seen_resolved[resolved]!r} resolve to the same "
                "file -- the accepted set must be exact, not contain duplicates or aliases"
            )
        seen_resolved[resolved] = entry_path
        if not resolved.is_file():
            raise PromotionReceiptError(f"artifact path {entry_path!r} does not exist")
        if is_generated_review_projection(workspace_root, entry_path, resolved):
            raise PromotionReceiptError(
                f"artifact path {entry_path!r} is a generated review projection (a witness rendering, "
                "the contact sheet, or the feature ledger) -- plan.md §16.6: these are review "
                "projections, never promotion inputs, and must never be listed in artifact_manifest"
            )
        witness_hash = _witness_promotion_hash_if_applicable(descriptor, workspace_root, entry_path, resolved)
        manifest.append({"path": entry_path, "hash": witness_hash or _sha256(resolved)})
    return manifest


def compute_promotion_id(cluster: str) -> str:
    """Deterministically derive promotion_id from `cluster` alone --
    mechanical, not a free-form caller-supplied string. `cluster` is
    itself schema-constrained to `^[a-z][a-z0-9-]*$` (docs/promotion-receipt-schema.json),
    so uppercasing it always yields a value starting with a letter and
    containing only [A-Z0-9-] -- exactly what promotion_id's own
    `^PROM-[A-Z][A-Z0-9-]*-[0-9]{3}$` pattern needs, with no separate
    validation required here (a malformed `cluster` is still caught by
    G1a on the assembled receipt before anything is written).

    No promotion lineage/sequence concept is modeled anywhere else in
    this pipeline, so the numeric suffix is always "001" -- this keeps
    promotion_id stable across a cluster's re-acceptances, which matters
    because other artifacts (docs/work-package-manifest-schema.json's
    own provenance.promotion_id) reference it by value; a promotion_id
    that changed on every re-acceptance would strand those references."""
    return f"PROM-{cluster.upper()}-001"


def _locate_artifact(descriptor: dict, workspace_root: Path, resolved: Path) -> tuple[str, dict | None] | None:
    """Determine an accepted artifact's kind (and crate, if crate-scoped)
    by matching its resolved parent directory against the project
    descriptor's own canonical directories -- project_descriptor.py's
    *_dir_for helpers, the exact same anchoring every validate_*.py
    module's own crate-wide scan already uses. External review, medium
    severity, fourth pass: matching by directory *basename* alone (e.g.
    parent.name == "_boundaries") let a fully schema-valid boundary
    contract at `junk/_boundaries/<id>.json` -- nowhere near any crate's
    real boundary directory -- have its schema_version trusted. A path
    that isn't under any crate's or the workspace's real canonical
    directory returns None (contributes nothing to schema_versions),
    exactly like any other non-kind artifact -- it is not specially
    rejected, since compute_artifact_manifest() already accepted it as
    an opaque hashed file; it simply isn't treated as a trustworthy kind
    instance."""
    if resolved.parent == evidence_dir_for(workspace_root):
        return "evidence", None
    if resolved.parent == conflict_dir_for(workspace_root):
        return "conflict_resolution", None
    for crate in descriptor["crates"]:
        if resolved.parent == boundary_dir_for(crate, workspace_root):
            return "boundary", crate
        if resolved.parent == interaction_dir_for(crate, workspace_root):
            return "interaction", crate
        if resolved.parent == exemption_dir_for(crate, workspace_root):
            return "exemption", crate
        if resolved.parent == protocol_debt_dir_for(crate, workspace_root):
            return "protocol_debt", crate
        if resolved.parent == witness_dir_for(crate, workspace_root):
            return "witness", crate
    return None


def _crate_context(crate: dict, workspace_root: Path, cache: dict[str, dict]) -> dict:
    """Real per-crate cross-file context -- interactions_by_id, G15's
    protocol-debt coverage, R2's boundary/exemption coverage -- built
    from the SAME functions pipeline.py's own cmd_validate_interaction/
    cmd_validate_exemption/cmd_validate_protocol_debt use, not
    re-derived ad hoc. Memoized per crate_dir since multiple accepted
    artifacts commonly belong to the same crate."""
    crate_dir = crate["crate_dir"]
    if crate_dir in cache:
        return cache[crate_dir]
    crate_root = (workspace_root / crate_dir).resolve()
    specs_search_root = workspace_root / crate["specs_search_root"]
    interactions_by_id = load_interactions_by_id(interaction_dir_for(crate, workspace_root))
    context = {
        "specs_search_root": specs_search_root,
        "interactions_by_id": interactions_by_id,
        "valid_debt_interaction_ids": valid_interaction_ids_from_crate(
            crate_root, protocol_debt_dir_for(crate, workspace_root), interactions_by_id
        ),
        "covering_boundary_edges": valid_boundary_edges_from_crate(
            crate_root, boundary_dir_for(crate, workspace_root), specs_search_root
        ),
        "valid_exemption_interaction_ids": valid_exemption_interaction_ids_from_crate(
            crate_root, exemption_dir_for(crate, workspace_root), interactions_by_id
        ),
    }
    cache[crate_dir] = context
    return context


def _validate_accepted_artifact(
    kind: str,
    crate: dict | None,
    path: Path,
    data: dict,
    workspace_root: Path,
    crate_context_cache: dict[str, dict],
    evidence_ids_cache: dict[str, set[str]],
) -> list:
    """Validate an accepted artifact against its own real, kind-specific
    validator WITH real cross-file context -- G2/G2+/G2++/G15/R2/G11 all
    run for real here, fail-closed, the same as Stage 4
    (pipeline.py's own cmd_validate_*) and approve(). External review,
    high severity, fourth pass: the previous version called each
    validator with no crate/workspace context at all, degrading every
    cross-file gate to a non-blocking info finding -- a *reviewed*
    exemption referencing a nonexistent interaction still passed, since
    only the schema's own required `review` field needed to be
    satisfied by hand."""
    if kind == "evidence":
        return _validate_evidence_data(path, data, _load_evidence_validator())
    if kind == "conflict_resolution":
        if "evidence_ids" not in evidence_ids_cache:
            evidence_ids_cache["evidence_ids"] = valid_evidence_ids(evidence_dir_for(workspace_root))
        return _validate_conflict_resolution_data(
            path, data, _load_conflict_resolution_validator(), evidence_ids_cache["evidence_ids"]
        )

    assert crate is not None  # every other kind is crate-scoped by _locate_artifact's own contract
    if kind == "witness":
        # No cross-file context needed (unlike boundary/interaction/
        # exemption/protocol_debt) -- validate_witness.py's own G2 needs
        # only the owning crate's specs_search_root, not
        # interactions_by_id/coverage sets, so _crate_context()'s
        # heavier per-crate graph is not built for this kind.
        specs_search_root = workspace_root / crate["specs_search_root"]
        return _validate_witness_data(path, data, _load_witness_validator(), specs_search_root)
    context = _crate_context(crate, workspace_root, crate_context_cache)
    if kind == "boundary":
        return _validate_boundary_data(path, data, _load_boundary_validator(), context["specs_search_root"])
    if kind == "interaction":
        return _validate_interaction_data(
            path, data, _load_interaction_validator(),
            context["valid_debt_interaction_ids"], context["covering_boundary_edges"],
            context["valid_exemption_interaction_ids"],
        )
    if kind == "exemption":
        return _validate_exemption_data(
            path, data, _load_exemption_validator(), context["interactions_by_id"]
        )
    if kind == "protocol_debt":
        return _validate_protocol_debt_data(
            path, data, _load_protocol_debt_validator(), context["interactions_by_id"]
        )
    raise AssertionError(f"unreachable: unknown kind {kind!r}")  # pragma: no cover


def compute_schema_versions(workspace_root: Path, descriptor: dict, artifact_paths: list[str]) -> dict[str, str]:
    """Deterministically compute schema_versions by validating each
    accepted artifact -- against its own real validator, WITH real
    cross-file context (_validate_accepted_artifact) -- and reading the
    `schema_version` it declares. Not a caller-supplied guess, not
    trusted from an unvalidated file, and not trusted from a file that
    merely sits under a directory sharing a kind's basename
    (_locate_artifact requires the real, descriptor-derived canonical
    location).

    An artifact located at a recognized kind's canonical directory that
    fails its own validator (error-severity findings) refuses the whole
    computation -- a promotion cannot silently exclude a broken artifact
    while still accepting it into artifact_manifest; it must be
    genuinely valid or the acceptance is refused outright. An artifact
    at no recognized canonical location contributes nothing. Two
    artifacts of the same kind declaring different schema_version
    values, once both are confirmed valid, is an internal inconsistency
    within this promotion and is refused too."""
    crate_context_cache: dict[str, dict] = {}
    evidence_ids_cache: dict[str, set[str]] = {}
    versions: dict[str, str] = {}
    for entry_path in artifact_paths:
        resolved = (workspace_root / entry_path).resolve()
        located = _locate_artifact(descriptor, workspace_root, resolved)
        if located is None:
            continue
        kind, crate = located

        try:
            data = json.loads(resolved.read_text())
        except (json.JSONDecodeError, UnicodeDecodeError, OSError) as e:
            raise PromotionReceiptError(
                f"{entry_path!r} sits at a recognized {kind!r} directory but is not readable, "
                f"parseable JSON: {e}"
            )
        if not isinstance(data, dict):
            raise PromotionReceiptError(
                f"{entry_path!r} sits at a recognized {kind!r} directory but is not a JSON object"
            )

        findings = _validate_accepted_artifact(
            kind, crate, resolved, data, workspace_root, crate_context_cache, evidence_ids_cache
        )
        errors = [f for f in findings if getattr(f, "severity", "error") == "error"]
        if errors:
            raise PromotionReceiptError(
                f"{entry_path!r} does not pass its own {kind} validator -- refusing to accept it into "
                "this promotion or trust its schema_version:\n"
                + "\n".join(f"  - {f}" for f in errors)
            )

        version = data.get("schema_version")
        if version is None:
            raise PromotionReceiptError(
                f"{entry_path!r} passed its own {kind} validator but declares no schema_version"
            )
        if kind in versions and versions[kind] != version:
            raise PromotionReceiptError(
                f"accepted artifacts disagree on {kind!r} schema_version: {versions[kind]!r} vs "
                f"{version!r} (from {entry_path!r})"
            )
        versions[kind] = version
    if not versions:
        raise PromotionReceiptError(
            "could not compute schema_versions from the accepted artifact set -- no accepted artifact "
            "sits at a recognized canonical directory (a crate's _boundaries/_interactions/_exemptions/"
            "_protocol_debt, or the workspace's evidence/_conflicts) with its own schema_version field"
        )
    return versions


_POLICY_VERSION_MARKER_RE = re.compile(
    r"^Policy version:\s*`?([a-z][a-z0-9-]*@[0-9]+(?:\.[0-9]+)*)`?\s*$", re.MULTILINE
)


def extract_policy_version(workspace_root: Path, policy_path: str) -> str:
    """Mechanically read policy_version from the accepted policy
    document's own content (docs/reliance-policy.template.md's own
    "Policy version: <name>@<major>.<minor>" line) -- not a free-form
    caller-supplied argument, and not just checked against an accepted
    artifact's filename stem.

    Exactly one marker line is required. External review, low severity,
    fourth pass: the previous version returned the *first* regex match,
    so a policy document containing two different "Policy version:"
    lines (e.g. "reliance-policy@1.2" and "reliance-policy@9.9") was
    silently accepted as whichever came first -- ambiguous, not
    verified. Zero matches or more than one are both hard stops."""
    resolved = workspace_root / policy_path
    try:
        text = resolved.read_text()
    except OSError as e:
        raise PromotionReceiptError(f"could not read policy document {policy_path!r}: {e}")
    matches = _POLICY_VERSION_MARKER_RE.findall(text)
    if len(matches) != 1:
        raise PromotionReceiptError(
            f"{policy_path!r} must have exactly one 'Policy version: <name>@<major>.<minor>' marker "
            f"line (docs/reliance-policy.template.md's own convention) -- found {len(matches)}"
        )
    return matches[0]


def build_receipt(
    promotion_id: str,
    cluster: str,
    reviewer: str,
    policy_version: str,
    schema_versions: dict[str, str],
    artifact_manifest: list[dict],
    accepted_at: str | None = None,
) -> dict:
    """Assemble a promotion-receipt/1.0 document. Pure data assembly --
    no filesystem access, no validation; accept_promotion() below does
    both, in that order."""
    return {
        "schema": "promotion-receipt/1.0",
        "promotion_id": promotion_id,
        "cluster": cluster,
        "reviewer": reviewer,
        "policy_version": policy_version,
        "schema_versions": schema_versions,
        "accepted_at": accepted_at or datetime.now(timezone.utc).date().isoformat(),
        "artifact_manifest": artifact_manifest,
    }


def _rollback_audit_log(review_log: Path, existed: bool, original_size: int) -> None:
    """Undo a prepared audit append while preserving the prior log --
    mirrors review_checkpoint.py's own approve_pair()-internal helper of
    the same shape, kept as an independent copy here rather than a
    cross-module import of a name that module treats as private."""
    if existed:
        with review_log.open("r+b") as stream:
            stream.truncate(original_size)
            stream.flush()
            os.fsync(stream.fileno())
    else:
        review_log.unlink(missing_ok=True)


def accept_promotion(
    workspace_root: Path,
    cluster: str,
    reviewer: str,
    policy_path: str,
    artifact_paths: list[str],
    descriptor_path: Path | None = None,
    accepted_at: str | None = None,
    review_log: Path | None = None,
) -> Path:
    """The dedicated Stage 4.5 acceptance operation (chainlink #45).

    `descriptor_path` defaults to `workspace_root / "project-descriptor.json"`
    (the same convention pipeline.py's own global --descriptor flag
    uses) -- its crates are what compute_schema_versions() anchors
    canonical directories and cross-file validation context to. Loading
    it, and therefore this whole operation, fails closed
    (ProjectDescriptorError propagates) if the descriptor is missing or
    invalid; a promotion cannot be accepted without knowing the real
    crate layout to validate against.

    `policy_path` (e.g. "docs/reliance-policy.md") must itself be one of
    `artifact_paths` -- its own content is where policy_version is read
    from (extract_policy_version), not a caller-supplied guess.

    Writes to <workspace_root>/specs/_promotions/<cluster>.json -- the
    same canonical directory scripts/validate_promotion_receipt.py's own
    check_naming anchors to. `review_log` defaults to
    `workspace_root / "ci" / "results" / "review_log.jsonl"` -- NOT
    review_checkpoint.REVIEW_LOG_DEFAULT, which is cwd-relative and so
    would silently write an external workspace's audit trail into
    whatever repo this happened to be invoked from.

    Refuses (PromotionReceiptError) before touching the filesystem at
    all if an artifact path, an artifact's own validity (including its
    real cross-file gates), the policy document, or -- chainlink #35 --
    the required witness set is bad: every declared (witness_required:
    true) feature belonging to `cluster` and having its own genuinely
    valid, unambiguous witness spec (validate_promotion_receipt.
    required_witness_paths(), reusing chainlink #29/#30's own
    descriptor-backed discovery and shared verbatim with that module's
    own validator so the two can never disagree about completeness)
    must be present in `artifact_paths`, or generation refuses outright
    rather than producing a receipt that silently omits evidence that
    was part of what was reviewed. Refuses
    (ApprovalRefused) without writing anything if the assembled receipt
    fails the real validator. Once past both checks, the audit entry and
    the receipt write happen as one transaction: the audit append is
    durable before the receipt is swapped into place, and a failure
    swapping the receipt in rolls the audit entry back -- there is no
    window where an accepted receipt exists with no corresponding audit
    entry, or vice versa. Returns the path written."""
    if not reviewer:
        raise ValueError("accept_promotion() requires a non-empty reviewer -- no default, no LLM-supplied value")
    if policy_path not in artifact_paths:
        raise PromotionReceiptError(
            f"policy_path {policy_path!r} must itself be one of the accepted artifacts"
        )
    if descriptor_path is None:
        descriptor_path = workspace_root / "project-descriptor.json"
    if review_log is None:
        review_log = workspace_root / "ci" / "results" / "review_log.jsonl"

    descriptor = load_project_descriptor(descriptor_path)

    try:
        required_witnesses = required_witness_paths(descriptor, workspace_root, cluster)
    except RequiredWitnessError as e:
        raise PromotionReceiptError(str(e))
    missing_witnesses = sorted(set(required_witnesses) - set(artifact_paths))
    if missing_witnesses:
        raise PromotionReceiptError(
            "declared (witness_required: true) feature(s) have a genuinely valid witness spec that "
            "is not included in this promotion's accepted artifact set: " + ", ".join(missing_witnesses)
        )

    target_path = workspace_root / "specs" / "_promotions" / f"{cluster}.json"
    artifact_manifest = compute_artifact_manifest(workspace_root, artifact_paths, descriptor)
    schema_versions = compute_schema_versions(workspace_root, descriptor, artifact_paths)
    policy_version = extract_policy_version(workspace_root, policy_path)
    promotion_id = compute_promotion_id(cluster)
    receipt = build_receipt(
        promotion_id=promotion_id,
        cluster=cluster,
        reviewer=reviewer,
        policy_version=policy_version,
        schema_versions=schema_versions,
        artifact_manifest=artifact_manifest,
        accepted_at=accepted_at,
    )

    validator = load_validator()
    findings = validate_data(target_path, receipt, validator, workspace_root, descriptor)
    errors = [f for f in findings if getattr(f, "severity", "error") == "error"]
    if errors:
        raise ApprovalRefused(
            f"generated promotion receipt fails validation, refusing to write {target_path}:\n"
            + "\n".join(f"  - {f}" for f in errors)
        )

    payload = json.dumps(receipt, indent=2) + "\n"
    audit_line = json.dumps(
        {
            "target_path": str(target_path),
            "classification": "generated",
            "reviewer": reviewer,
            "reviewed_at": receipt["accepted_at"],
            "validation": "checked",
            "logged_at": datetime.now(timezone.utc).isoformat(),
        }
    ) + "\n"

    target_path.parent.mkdir(parents=True, exist_ok=True)
    review_log.parent.mkdir(parents=True, exist_ok=True)

    log_existed = review_log.exists()
    original_log_size = review_log.stat().st_size if log_existed else 0
    audit_touched = False
    try:
        with review_log.open("a") as stream:
            audit_touched = True
            stream.write(audit_line)
            stream.flush()
            os.fsync(stream.fileno())
    except Exception:
        if audit_touched:
            _rollback_audit_log(review_log, log_existed, original_log_size)
        raise

    fd, temp_name = tempfile.mkstemp(prefix=f".{target_path.name}.", suffix=".pending", dir=target_path.parent)
    temp_path = Path(temp_name)
    try:
        with os.fdopen(fd, "w") as stream:
            stream.write(payload)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temp_path, target_path)
    except Exception:
        temp_path.unlink(missing_ok=True)
        _rollback_audit_log(review_log, log_existed, original_log_size)
        raise

    return target_path
